// Generated by CoffeeScript 1.9.1
(function() {
  var autoPlay, navBannerContent, navBannerContentMaxIndex, navBannerIndex, navBannerNext, navBannerPrev, navScroll, navScrollHeight, pics, picsIndex, picsNavs, scrollTimeHandler, startScroll, timeHandler, titleMenu;

  pics = $('#pics img');

  picsNavs = $('#picsNav li');

  picsIndex = 0;

  timeHandler = null;

  autoPlay = function() {
    pics.fadeOut(500).eq(picsIndex).fadeIn(500);
    picsNavs.removeClass('on').eq(picsIndex).addClass('on');
    if (picsIndex > 2) {
      picsIndex = -1;
    }
    picsIndex++;
    return timeHandler = setTimeout(autoPlay, 4000);
  };

  autoPlay();

  picsNavs.on('click', function() {
    var index;
    clearTimeout(timeHandler);
    index = $(this).index();
    picsIndex = index;
    return autoPlay();
  });

  navBannerPrev = $('#nav-banner-bottom-prev');

  navBannerNext = $('#nav-banner-bottom-next');

  navBannerContent = $('#banner-bottom-content');

  navBannerIndex = 0;

  navBannerContentMaxIndex = navBannerContent.find('.box').length;

  navBannerPrev.click(function() {
    if (navBannerIndex === 0) {
      return;
    }
    navBannerIndex--;
    return navBannerContent.animate({
      left: -290 * navBannerIndex
    }, 300);
  });

  navBannerNext.click(function() {
    if (navBannerIndex === navBannerContentMaxIndex - 3) {
      return;
    }
    navBannerIndex++;
    return navBannerContent.animate({
      left: -290 * navBannerIndex
    }, 300);
  });

  navScroll = $('#nav-bottom-scroll');

  navScrollHeight = navScroll.height();

  scrollTimeHandler = null;

  navScroll.children().clone().appendTo(navScroll);

  startScroll = function() {
    var moveDis;
    moveDis = parseInt(navScroll.css('top')) - 1;
    if (moveDis < -navScrollHeight) {
      moveDis = 0;
    }
    navScroll.css("top", moveDis + "px");
    return scrollTimeHandler = setTimeout(startScroll, 66);
  };

  startScroll();

  navScroll.mouseenter(function() {
    return clearTimeout(scrollTimeHandler);
  });

  navScroll.mouseleave(function() {
    return startScroll();
  });

  titleMenu = $('.container-bottom-in .menu');

  titleMenu.click(function() {
    var index, menus;
    menus = $(this).parent().find('.menu');
    index = menus.index($(this));
    menus.removeClass('on').eq(index).addClass('on');
    return $(this).parent().siblings('.box').fadeOut(0).eq(index).fadeIn(0);
  });

}).call(this);
